### ISSUE TITLE
Anti Force Op book

### ISSUE THREAD

**Issue by TheIntelloBox** [DoNotSpamPls/eZProtector#10]
Hey,

One of my players have a force op book hack.
Could you solve the problem with ezprotector ? :)

Thanks.

**Comment by DoNotSpamPls** [comment]
The "ForceOP" hack relies heavily on people with admin permissions. as long as your admins arent dumb you shouldnt need this

**Comment by TheIntelloBox** [comment]
Yeah but would be nice too

**Comment by DoNotSpamPls** [comment]
I don't want to add features which prevent admin stupidity - there are other plugins that can do that. eZProtector is focused on adding features that block things admins can't necessarily control manually. Sorry, but this probably won't be added any time soon.
