### ISSUE TITLE
Color Codes for Custom-Version.

### ISSUE THREAD

**Issue by TheIntelloBox** [DoNotSpamPls/eZProtector#13]
Hey,

Could you add color codes for Custom-Version ?

Thanks !

**Comment by ThatGamerBlue** [comment]
Should already work using & or § color codes

**Comment by DoNotSpamPls** [comment]
Athough it's not tested, there isn't any reason that it shouldn't work with just & (and § certainly works).
But I will test before closing the issue

**Comment by TheIntelloBox** [comment]
&c doesn't work

**Comment by DoNotSpamPls** [comment]
Fixed in 761da1c

**Comment by TheIntelloBox** [comment]
Where can I download ?

**Comment by DoNotSpamPls** [comment]
@TheIntelloBox It will be available in the next release of eZProtector, but I'd like to fix some more bugs before releasing that.
