### ISSUE TITLE
Error when doing /version ! :D

### ISSUE THREAD

**Issue by TheIntelloBox** [DoNotSpamPls/eZProtector#17]
Hey ! :D 

If I do /ver, there is a problem ! :D In fact, see my screenshot ! :D
http://www.noelshack.com/2018-24-7-1529251252-error-paper.jpg ! :D

And there is an error ! :D
https://hastebin.com/ibiligefol.md ! :D 

Thanks for fixing it ! :D 
Have a nice morning/day/evening/night ! :D 
TheIntelloBox. :D

**Comment by DoNotSpamPls** [comment]
That error is 100% unrelated to eZProtector, but if custom-version is set to true, then there might be a problem (although there shouldn't be, since custom version was tested on Paper)

**Comment by TheIntelloBox** [comment]
Yeah it is : https://hastebin.com/mudoxiruce.bash ! :D

**Comment by TheIntelloBox** [comment]
So, any news ? :D

**Comment by DoNotSpamPls** [comment]
That error is Paper being weird, update to the latest version and try again. I'll test it myself, but I haven't seen any problems with the command.

**Comment by DoNotSpamPls** [comment]
I tested it on my environment (just a few builds older than yours) and I was unable to find an issue. Maybe another plugin is messing with it. Also, if Paper can't check for a new version then there is a problem with your environment overall. If you have any errors or if there is still a problem, feel free to reopen this issue with more information.
