### ISSUE TITLE
Adding mod blocking for the Wurst Cheat Client

### ISSUE THREAD

**Issue by KarlOfDuty** [DoNotSpamPls/eZProtector#18]
It would be nice to add blocking of the Wurst cheat client itself and/or it's mods. It is the client most commonly used by cheaters on our server.

**Comment by ThatGamerBlue** [comment]
Not possible. Doesn't relay any information that it's there to the server for obvious reasons.

**Comment by KarlOfDuty** [comment]
That makes sense, thank you.
