### ISSUE TITLE
/ver doesn't block plugins display. :D

### ISSUE THREAD

**Issue by TheIntelloBox** [DoNotSpamPls/eZProtector#20]
Hello ! :D 

I found a bug ! :D 
In fact, if you do /ver A and you press the TAB key, you can see the plugins, for example of my server you can see ASkyBlock, etc. :D

**Comment by DoNotSpamPls** [comment]
You need to enable the tab completion block, if you enable it the players won't be able to do that anymore.

**Comment by TheIntelloBox** [comment]
tab-completion:
  blocked: true
  warn:
    # If this option is set to true and a player holds the Tab key, they'll be spammed with the message below
    enabled: true
    message: '%prefix% &cYou don''t have permission to tab-complete commands.'
  notify-admins:
    # If this is set to true, players with notify permissions will also get spammed if a player holds the Tab key.
    enabled: false
    message: '%prefix% %player% tried to tab-complete a command. &4(%command%)'
  punish-player:
    # This shouldn't really be necessary, but it's here for convenience. It's not recommended to punish a player for pressing the Tab key in the chat!
    enabled: false
    command: 'kick %player% %errormessage%'

**Comment by DoNotSpamPls** [comment]
This doesn't help, there isn't any problem in my test environment.

**Comment by TheIntelloBox** [comment]
So I have to install HideAndCustomPlugins to fix this problem. :x
