### ISSUE TITLE
Translation of "There are 6 plugins:" and "This server is running server version:". :D

### ISSUE THREAD

**Issue by TheIntelloBox** [DoNotSpamPls/eZProtector#21]
Hello ! :D 

Could you add the ability to translate "There are 6 plugins:" and "This server is running server version:" ? :D 

Thanks for adding it that ! :D

**Comment by DoNotSpamPls** [comment]
Those features are meant to mimic exactly how Bukkit shows it. If you want to show something else, I think your best solution would be to replace the messages with [ChatControl](https://www.spigotmc.org/resources/chatcontrol.271/). Translation of those kind of messages is out of the scope of eZProtector.

**Comment by TheIntelloBox** [comment]
How can I replace this message with ChatControl ? :D

**Comment by DoNotSpamPls** [comment]
I'm not an expert in that plugin, you should ask the author, but iirc there is a filter feature for certain phrases to be replaced.
