### ISSUE TITLE
1.13 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [DoNotSpamPls/eZProtector#24]
Hey,

The plugin doesn't work in 1.13.

Thanks for fixing it ! :D

**Comment by DoNotSpamPls** [comment]
No shit sherlock.
I think it's done, but i'll *not* release it until some mods actually release their 1.13 versions, otherwise many will complain

**Comment by TheIntelloBox** [comment]
Okay. :)

**Comment by TheIntelloBox** [comment]
1.13 builds are released.
