### ISSUE TITLE
NPEs for DamageIndicators and ReiMinimap

### ISSUE THREAD

**Issue by smellyonionman** [DoNotSpamPls/eZProtector#25]
**Describe the bug**
Nobody but ops can connect to the server when either DamageIndicators or ReiMinimap are blocked.

**To Reproduce**
1. Enable either blocker
2. De-op yourself or a trusted friend
3. Ensure no bypasses are enabled
4. Log in

**Expected behavior**
Play Minecraft!

**Screenshots**
Here are two screenshots, one of each error:
`smellycraft.com/downloads/error-damageindicator-block.png`
`smellycraft.com/downloads/error-reiminimap-block.png`

**Server Version:**
Paper build 1552

**Comment by DoNotSpamPls** [comment]
With eZProtector no longer supporting 1.7, I'm going to be closing this issue, since both of these mods don't support 1.8 or above anyway
