### ISSUE TITLE
Issues with BungeeCord when logging in

### ISSUE THREAD

**Issue by DoNotSpamPls** [DoNotSpamPls/eZProtector#27]
People are reporting these kinds of errors:
```
- java.lang.RuntimeException: VarInt too big
- badly compressed packet: size of 13 is below server threshold of 512
- java.util.zip.DataFormatException: invalid distance too far back
```

Need to investigate.

**Comment by ThatGamerBlue** [comment]
Can't reproduce it myself, you found a good way to? My setup: https://i.imgur.com/nTMyjtL.png

**Comment by DoNotSpamPls** [comment]
I haven't been able to reproduce it either, but it's something that some users are reporting. Need more information from them about their setup.

**Comment by DoNotSpamPls** [comment]
Closing this issue, hopefully someone will report if they have any issues.
