### ISSUE TITLE
[Issues] - TabCompletation in 1.13.1 is not getting really block - the hoverpart :(

### ISSUE THREAD

**Issue by CloudeLecaw** [DoNotSpamPls/eZProtector#28]
Simply typ /

![image](https://user-images.githubusercontent.com/12080017/46997100-187f7e00-d11f-11e8-85be-95079f24a0ea.png)

![image](https://user-images.githubusercontent.com/12080017/46998271-5a5df380-d122-11e8-86f5-59a03558120c.png)

well the list is Long but i can scroll all as Player

an other example: i write /pl
![image](https://user-images.githubusercontent.com/12080017/46997166-5086c100-d11f-11e8-94ca-8eeb3e2be863.png)

Well this just means that Tabcompletation blocker is not working for Spigot 1.13.1 :(

**Comment by DoNotSpamPls** [comment]
That is because of Mojang's new brigadier system - it doesn't use tab complete packets, so I'm unable to block them that way. It *might* be added in the future when I find a way, but no promises.

**Comment by CloudeLecaw** [comment]
Well i have no clue how the Developer Zrips sloved it. but in his Plugin CMI you just see the /cmi [Command] in this new tab"hover"System if you have the permission for it.

may this can give you a suggetion.

**Comment by DoNotSpamPls** [comment]
That's for his own command, I can do that for /ezp too. The problem is that I'm working with other plugin commands, which can't be modified as easily

**Comment by DoNotSpamPls** [comment]
Since commit f3396cb and version 4.4.2, commands added to the config list are completely removed from Brigadier's tree, so it's as if they don't even exist!
