### ISSUE TITLE
Console Spam on Player Login

### ISSUE THREAD

**Issue by mercurialmusic** [DoNotSpamPls/eZProtector#29]
**Describe the bug**
Getting this spam every time someone logs in using ezProtector 4.4.1: https://pastebin.com/0cwA2Bf6

Doesn't seem to affect their login, and considering it's happening for every player I highly doubt they're all using schematica. 

**Server Version:**
git-Spigot-2474d93-e693496 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by DoNotSpamPls** [comment]
Should be resolved in commit e701ef5, will release 4.4.2 soon enough.
