### ISSUE TITLE
TabComplet still works :( in 1.13.2

### ISSUE THREAD

**Issue by CloudeLecaw** [DoNotSpamPls/eZProtector#30]
Well you closed my Thread with the 4.4.2 Update..but the Problem is remaining

As Player i do /TAB and voila..

![image](https://user-images.githubusercontent.com/12080017/48262086-861e8180-e421-11e8-82b4-a94f667c5df4.png)
(this is just a part of the Long list)

so the Tab Complet does not work in spigot 1.13.2 :(

**Comment by DoNotSpamPls** [comment]
Only commands listed in the tab-completion blocked list are removed.
If you want to disable that list *entirely*, you are better off setting tab-completion to -1 in spigot.yml

**Comment by CloudeLecaw** [comment]
Well no.. i want that Player just can TAB the commands that they have permission for..
a black list...this list would be endless then. 🥉 
may a whitelist would be nice too..

Spigots tab-completation -1 is the worst solution because it also blocks all for admins and everone even for the owner.

Your Blacklist also is no good solution. it blocks the listet for all.

**Comment by DoNotSpamPls** [comment]
You're right, I didn't include the permission for bypassing that, I'll include it in the next version.
Changing the system to allow changing it to a whitelist would break existing configurations and also would be a bit complicated imo. I don't think there's that much of an issue having a long list, after all all servers have plenty of space.

Also, remember, properly coded plugins won't even show up their commands on that list if you don't have the permission to use the commands - for example, eZProtector doesn't show the /ezp command if you don't have the ezprotector.reload command 😃
