### ISSUE TITLE
Console Spam Strikes Again!

### ISSUE THREAD

**Issue by mercurialmusic** [DoNotSpamPls/eZProtector#31]
**Describe the bug**
Still getting the console spam on player login with ezP 4.4.2: https://pastebin.com/0cwA2Bf6

**Server Version:**
git-Spigot-2474d93-ca22de3 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by mercurialmusic** [comment]
Seeing your other issue, I am using a Bungee setup as well, if that sheds additional light on the situation.

**Comment by DoNotSpamPls** [comment]
hell, empty channels are also in the `no :` category. I know why this bug is, will fix pretty soon
