### ISSUE TITLE
Rework tab completion

### ISSUE THREAD

**Issue by DoNotSpamPls** [DoNotSpamPls/eZProtector#32]
The tab completion option seems to be a bit confusing to users. In the future, these features should be added:
* Hide all commands when you type /\<tab>
* Have it configurable so it can be either all commands, blacklist or whitelist ~~(i'm not really keen on the whitelist idea, but we'll see)~~

Related: #30

**Comment by DoNotSpamPls** [comment]
This is *finally* being worked on :eyes:

**Comment by DoNotSpamPls** [comment]
Version 1.1.0 (to be released in a few days, hopefully) resolves this issue! 
The tab completion module has a new configurable option `whitelist`, defaulting to false.
If you decide to enable that, only commands in the list will be able to be tab completed.

(Hiding all commands will not be added to the plugin, for that you can just set `tab-complete` to -1 in your spigot.yml config)

**Comment by bobhenl** [comment]
I don't see whitelist option on bungee

**Comment by DoNotSpamPls** [comment]
@Volgeop It's available in the beta version of eZProtector, which can be downloaded [here](https://github.com/DoNotSpamPls/eZProtector/actions/runs/106669646)
