### ISSUE TITLE
eZprotector 

### ISSUE THREAD

**Issue by Andrew909** [DoNotSpamPls/eZProtector#35]
**Describe the bug**
Not sure if this is a bug or not but have tried many things and there still seems to be an issue. In the blocked commands for opped players I have several commands blocked for my admins, yet I still want to use the commands, I put my name into the bypassed players list and I still can't do the commands.

**Expected behavior**
I wanted it so I could use the commands but not my admins. I have got a couple of screenshots below to see if I am doing anything wrong, however I have tried many things.

**Screenshots**
[My account](http://prntscr.com/lrm3in) That account has bypass, yet still can't execute the command!
[My Config](http://prntscr.com/lrm0ic) That is the config setup.
**Server Version:**
Server Version is 1.10.2 (Spigot)

**Additional context**
I hope you can get this sorted as soon as possible.

**Comment by DoNotSpamPls** [comment]
This feature was removed a long time ago, use proper permissions and not OP 😃
