### ISSUE TITLE
Adding Forge Blocking for 1.13.2

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [DoNotSpamPls/eZProtector#37]
**Describe the bug**
As it says in the config file, blocking plugins isn't supported in 1.13. Could you please add support for forge? Someone came on my server and said it supports 1.13, and if it doesn't it is open source. Anyways, I'd like to block it to prevent injected ghost clients & all mods.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Server Version:**
CraftBukkit version git-Spigot-b0f4c22-d5e9688 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by DoNotSpamPls** [comment]
Forge doesn't even exist yet - it's still in beta and no mods support it. I'll be adding support for it once I can test it properly.

**Comment by PiggiesGoSqueal** [comment]
Okay, thanks

**Comment by PiggiesGoSqueal** [comment]
I know you saw my post here:
https://github.com/dvargas135/eZProtector/issues/72
So I'm just updating this post so it's in the correct location. Thanks!


> Forge 1.13.2 has been released, so could you please add a block for it? Thank you! :)

> Link: https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.13.2.html

**Comment by DoNotSpamPls** [comment]
Latest version **should** block Forge correctly. Let me know if that's not the case.
