### ISSUE TITLE
TAB Complete Bug

### ISSUE THREAD

**Issue by ghost** [DoNotSpamPls/eZProtector#39]
With the latest version of EZP on Paper 1.12.2 with a type / and tab it will works!

**Comment by DoNotSpamPls** [comment]
The plugin doesn't remove that functionality, it's meant to block `/plugins <tab>` for example. You can set `tab-complete` to -1 in spigot.yml to get what you want. I know the behaviour of that certain eZP feature is confusing, so I'm planning to rework it in the future (#32 is the tracking issue for that)
