### ISSUE TITLE
Tab completion cannot be blocked through Ezprotector

### ISSUE THREAD

**Issue by SpringGrim** [DoNotSpamPls/eZProtector#41]
Server version: 1.13.2
Plugin version: 4.4.2

Issue: putting this option in the config:

"tab-completion:
  blocked: true"

but it still doesn't block anything (I tested with non-op accounts too)

_Yes i know I can block tab completion in spigot.yml, but the text is red and i would like to have it cyan like it used to be in 1.12_

**Comment by DoNotSpamPls** [comment]
When you enable tab completion in eZProtector for 1.13, all commands listed in the config get removed from the list sent to the client. I know it's a bit confusing at the moment, and I'm planning to rework it a bit in the future

**Comment by SpringGrim** [comment]
Ohh daym okay.
Thanks for clarifying.

**Comment by DoNotSpamPls** [comment]
Closing this since #32 is the tracking issue for this behaviour
