### ISSUE TITLE
1.14 Support

### ISSUE THREAD

**Issue by darksaid98** [DoNotSpamPls/eZProtector#42]
**Describe the feature you'd like to have implemented**
Requesting a build with 1.14.* compatibility. It appears the version check is disabling the plugin.

Plugin version: eZProtector v4.4.2
Spigot API version: 1.14.1-R0.1-SNAPSHOT

**Error message**
```
[Server thread/INFO]: [eZProtector] Enabling eZProtector v4.4.2
[Server thread/ERROR]: [eZProtector] eZProtector is not supported on versions lower than 1.12.2!
[Server thread/INFO]: [eZProtector] Disabling eZProtector v4.4.2
```

**Comment by DoNotSpamPls** [comment]
The latest version on the CI has the check temporarily removed, use that for now while I push out a release version.

**Comment by darksaid98** [comment]
Awesome, thanks a lot.
