### ISSUE TITLE
custom-commands

### ISSUE THREAD

**Issue by x1p** [DoNotSpamPls/eZProtector#44]
**Describe the bug**
custom-commands does not block very much things.
Some things works decent, some plugins still listen to the command and response to that.
Example: many plugins have a sort of info output if you try the base command. These commands will still execute and bypasses eZProtector.

**To Reproduce**
1. Start server with eZProtector
2. try for example to execute /jumpto (a worldedit command)
3. check the output: You are not permitted to do that. Are you in the right mode?

**Expected behavior**
It would be nice if eZProtector can block all commands stated in the config

**Server Version:**
Paper 1.13.2 build 634
eZProtector version 1.0.0 (compiled from github)

**Comment by DoNotSpamPls** [comment]
Hmm, can you send me your config? Not sure why that would happen.

**Comment by x1p** [comment]
Sure. https://pastebin.com/4iGsmk06

My guess is that some plugins have a lower priority and therefore still listen to the command.

Edit: [This plugin](https://www.spigotmc.org/resources/tab-1-8-x-1-14-4-reborn.57806) is an example of a plugin which has the /tab command at the lowest priority possible. It's not interceptable by any means.

**Comment by DoNotSpamPls** [comment]
I'm unable to reproduce the issue, as seen [here](https://ranked.is-la.me/7PaR7Xz.gif).
Commit ef2a1fc might fix it, although I'm not 100% sure.

**Comment by x1p** [comment]
Unfortunately not. The particular plugin still reacts to the command too.
Meanwhile I have an other solution so there is no urgency.
