### ISSUE TITLE
1.14.3 Support

### ISSUE THREAD

**Issue by x1p** [DoNotSpamPls/eZProtector#45]
**Describe the bug**
eZProtector for paper does not recognize 1.14.3
Works on 1.14.2 though
Startup log:
```
[14:07:47 INFO]: [eZProtector] Enabling eZProtector v1.0.0
[14:07:47 ERROR]: [eZProtector] eZProtector is not supported on versions lower than 1.12.2!
[14:07:47 INFO]: [eZProtector] Disabling eZProtector v1.0.0
```

**To Reproduce**
1. Start paper 1.14.2
2. Check to see it loads
3. Start paper 1.14.3

**Expected behavior**
Run like on 1.14.2

**Screenshots**

**Server Version:**
Paper 1.14.3
eZProtector version 1.0.0 (compiled from github)

**Comment by DoNotSpamPls** [comment]
This was because of a breaking change in Spigot, please update your server to the very latest 1.14.3 version of Spigot and the error will go away :)
