### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by x1p** [DoNotSpamPls/eZProtector#46]
**Describe the bug**
Somehow the tab completion is not blocked anymore.
If the commands are executed anyways, the eZProtector message appears so that parts still works. It used to work, somehow it got broken.

**To Reproduce**
1. Download the latest Waterfall
2. Download the 1.0.0 release from the release tab from Juli 23th 2019
3. Let the default config extract
4. Log in with 1.14.4 client on a 1.14.4. paper server
5. Execute /ican<tab> and see if icanhasbukkit appears.

**Expected behavior**
I would have expect that all given commands are blocked.

**Screenshots**

**Server Version:**
Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290 + eZProtector-waterfall-1.0.0
Paper 1.14.4 server
Client 1.14.4

**Additional context**
I'm haven't figured out what changed since it did work. I will test further when I have the time.

**Comment by x1p** [comment]
The conclusion is that eZProtector for Waterfall only blocks tab-completion on the proxy.

Although the custom-commands do work for both proxy and paper.

(This might conflict if eZProtector is installed on both proxy and paper.
E.G: if icanhasbukkit is configured in both proxy version of eZ and the paper, the proxy takes care of the message before the eZ-paper gets the change.)

**Comment by DoNotSpamPls** [comment]
This is working as intended - the events that process tab completion only work for proxy commands, that's a limitation of the event itself. If you want to block tab completion for servers commands, you have to have eZP on both the proxy and the server (no conflict should happen as far as I'm aware)
