### ISSUE TITLE
Different levels of blocking tab-completion

### ISSUE THREAD

**Issue by x1p** [DoNotSpamPls/eZProtector#47]
**Describe the feature you'd like to have implemented**
2 Level blocking tab completion:
Level 1: for staff only commands
Level 2: bypass for no one (or only OP) for 90% of the unnecessary/dangerous commands/aliases

**Is your feature request related to an existing problem? Please describe.**
In my opinion there are (min) 2 levels of blocking tab completion:
1. Commands that only staff needs, and not players.
2. Complete junk commands that no one want to see/use
eZProtector can only block commands, or give someone bypass. If staff has has the bypass, they see all commands, including all junk commands which nobody needs.
If there would be 2 (or more) levels of blocking, there could be a way to always block the mess, and reveal the commands staff really needs.

**Additional context**
A workaround could be that the proxy version of eZProtector could also block paper commands (see issue #46) Then a 2 level restriction could be made by blocking all the mess in the proxy version, leaving the real useful commands to the paper version of eZProtector to block that for only the players and give staff the bypass on the paper servers behind the proxy.

**Comment by DoNotSpamPls** [comment]
Your workaround isn't possible, because the `TabCompleteEvent` and `ProxyDefineCommandsEvent` I use on the proxy version have no idea that the backend server commands even exist. 

For the suggestion itself - while it's an interesting idea, I feel like it would overcomplicate the plugin without much gain. If you think a command is completely useless, you could open the plugin's `plugin.yml` file and remove the command from there, effectively deleting it.

**Comment by DoNotSpamPls** [comment]
After thinking about it, I think the best way to go would be to add a per-command bypass permission (for example `ezprotector.bypass.tabcomplete.help`). This would allow flexibility, while not overcomplicating the configuration. Let me know if you have any objection to this idea.

**Comment by x1p** [comment]
No objection
The number of needed bypasses is just a few at most.

**Comment by bobhenl** [comment]
Hi could you add atleast whitelist or groups there (as different levels)? Also to bungee version

**Comment by DoNotSpamPls** [comment]
This feature is now live 😃
