### ISSUE TITLE
Adding a whitelist-commands to sections which block commands

### ISSUE THREAD

**Issue by Flavourized** [DoNotSpamPls/eZProtector#5]
**Describe the feature you'd like to have implemented**
This suggestions will create an option called `whitelist-commands:` for sections of the plugin which block certain commands. Whitelisted commands will not be interfered with by EZP. Instead they will be run as normal commands. 

This will allow the server to check if the user has access to the command, etc. 

**Is your feature request related to an existing problem? Please describe.**
This will allow us to use hidden-syntax for conflicting commands on our server, while keepign the rest blocked.

**Comment by DoNotSpamPls** [comment]
This was added in commit 3c9883c and will be published to Spigot, along with other improvements shortly.
If you have any other suggestions, feel free to open a new issue 😃
