### ISSUE TITLE
1.15.2 Support

### ISSUE THREAD

**Issue by ziipen** [DoNotSpamPls/eZProtector#50]
-snip-

**Comment by DoNotSpamPls** [comment]
Any commands listed in the tab-complete section are removed from that list ([this method](https://github.com/DoNotSpamPls/eZProtector/blob/master/paper/src/main/java/com/github/donotspampls/ezprotector/paper/listeners/BrigadierListener.java) is the one that does it)

If you want to disable that entirely, set tab-complete to -1 in spigot.yml

**Comment by ziipen** [comment]
Thanks, it is now fixed.
