### ISSUE TITLE
Custom commands message on Waterfall

### ISSUE THREAD

**Issue by x1p** [DoNotSpamPls/eZProtector#51]
**Describe the bug**
When a `custom-commands` is blocked by the waterfall version of eZProtector, the `error-message` is shown twice.

**To Reproduce**
1. Bungee + paper server with both eZProt on it
2. Enable custom commands to block `- op`
3. Set a special message on the waterfall version of EZ, and a different one the paper server
4. Join and execute /op
5. See 2 messages
6. Turn of the WF custom commands and restart WF
7. Join and execute /op
8. Check the paper custom-command-error-message

**Expected behavior**
I would expect the waterfall version to block the command and warn the player using one single error message

**Screenshots**
-

**Server Version:**
Waterfall version git:Waterfall-Bootstrap:1.15-SNAPSHOT:de7b945:339 by md_5

**Additional context**
-

**Comment by DoNotSpamPls** [comment]
I don't think you need the plugin on both instances - try removing it from the Paper server and check the results.

**Comment by x1p** [comment]
Indeed, when both respond, the bungee message is send twice.
I would expect them both to respond resulting in 2 different messages or one to prevail above the other.
Anyway. It's solved
