### ISSUE TITLE
[Request] Support for Fabric

### ISSUE THREAD

**Issue by mercurialmusic** [DoNotSpamPls/eZProtector#52]
**Describe the feature you'd like to have implemented**
I humbly request support for blocking the modloader Fabric. Since many servers have blocked Forge this seems to be the next thing people are turning to to load their mods. 

I'll also happily support the development (whether implemented or not) if you have a PayPal donation link/email?

**Comment by DoNotSpamPls** [comment]
Commit 5e39cd9 should have added what you are asking for. If you do not want to reset your config, add this to the mods section:
```
fabric:
    block: false
    warning-message: '%prefix% &e%player% &ftried to join while having Fabric installed'
    punish-command: kick %player% &4The Fabric mod is not allowed.
```

[Paper version](https://github.com/DoNotSpamPls/eZProtector/releases/download/1.1.0/eZProtector-Paper.jar)
[Waterfall version](https://github.com/DoNotSpamPls/eZProtector/releases/download/1.1.0/eZProtector-Waterfall.jar)

Let me know if something doesn't work!

P.S. While donations are in no way required or a guarantee for a feature, they are very much appreciated 👀
My PayPal can be found [here](https://www.paypal.me/donotspampls)
