### ISSUE TITLE
Mod blocking

### ISSUE THREAD

**Issue by Srborjaa** [DoNotSpamPls/eZProtector#53]
Hi, that's not a report, but I've seen that in the config:

```
# This section allows you to block various mods (and even punish players for some of them!)
# Most of these **do not** work for 1.13 or above
```

What mods are not blocked in 1.13, 1.14 and 1.15 ?

Thanks

**Comment by DoNotSpamPls** [comment]
What version of eZProtector are you using?

**Comment by Srborjaa** [comment]
I've downloaded it 10 minutes ago from the GitHub page so I'm using the last one.

**Comment by DoNotSpamPls** [comment]
That message is fairly outdated - the only mod that isn't blocked on 1.13+ is Schematica, simply because there is no 1.13 version for it.
