### ISSUE TITLE
Standard error instead of custom message.

### ISSUE THREAD

**Issue by qygEkSKD7CfwNc3n** [DoNotSpamPls/eZProtector#56]
**Is it possible to add an option (true / false or placeholder) to call the standard client response about a non-existent function instead of a custom message.**

```
custom-commands:
  blocked: true
  **error-message**: '&7[&aeZProtector&7]&f You don''t have the permission to use this command! &4(%command%)'
```

The unique reaction of the server is already a hint of the presence of a plugin. Calling a standard error about a non-existent command will resolve this issue.

**Comment by SrBedrock** [comment]
The standard error message can be changed according to each server and is located in the spigot.yml file.
You can change the configuration of the plugin and put the message below:
```yml
messages:
  unknown-command: Unknown command. Type "/help" for help.
```

**Comment by qygEkSKD7CfwNc3n** [comment]
Oh. Thank you for your comment. What I missed is that the server is handling this message. I thought the client was doing it ..

**Comment by qygEkSKD7CfwNc3n** [comment]
@DoNotSpamPls, it would be great to somehow use interception of the error text 💁‍♂️

**Comment by DoNotSpamPls** [comment]
You can just change the error message to be the same as the default one
