### ISSUE TITLE
tab-completion does not work

### ISSUE THREAD

**Issue by SrBedrock** [DoNotSpamPls/eZProtector#57]
**Describe the bug**
tab-completion option is not working in version 1.16.x

**To Reproduce**
1. Install the plugin;
2. Add commands in the tab-completion option;
3. Use tab and see the commands appearing in the command suggestion.

**Expected behavior**
Commands listed in the tab-completion option do not appear for players without permission.

**Server Version:**
1.6.1, 1.6.2 and 1.6.3

**Comment by DoNotSpamPls** [comment]
I have released a new version of the plugin - the tab complete module has been reworked. Could you try with that one to see if there are any issues?
