### ISSUE TITLE
only non-op empty message when join

### ISSUE THREAD

**Issue by arts7493** [DoNotSpamPls/eZProtector#58]
**Describe the bug**
A clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/3336813/102861383-e7273900-4472-11eb-9ef2-9d645f2603fd.png)

**Server Version:**
Include your server version here.
1.15.2 paper
**Additional context**

**Comment by DoNotSpamPls** [comment]
https://github.com/DoNotSpamPls/eZProtector/wiki/FAQ#i-get-blank-lines-when-i-first-log-in-why-is-that
