### ISSUE TITLE
SmartMoving blocking doesn't work.

### ISSUE THREAD

**Issue by CloudeLecaw** [DoNotSpamPls/eZProtector#6]
first of all, the tip with reseting the config..help but is no solution, for all that did it.. i hope for you you had a backup fo your config 
now to the error.
In the New Version 4.2.2 Players that try to login the server (Not Admins!)
login and get kicked a few ticks later with this meassge:

![image](https://user-images.githubusercontent.com/12080017/40148779-24df64f2-5970-11e8-9078-a8e642081349.png)

The reason that Admins login without problem just means they using one of the bypasses that kicks the client for players.

i read in the thread that reseting the config helped.
So this means something of the true/false defaultvalues that is changed by the owner causes this issues.
So i tested it true/false option by option as player (with extra console access for reloading)... option by option: first started with all options false. (means all is disabled) -> set first to option true -> reloaded plugin, reloged charakter -> checked result. set secound option to true -> reloaded plugin, reloged charakter -> checked result...and so on....until..i got my wanted result (the login error)...
the result...
the LAST option "smartmoving" causes this error if it is set to true.
```
  smartmoving:
    block: true
```
change it back to:
```
  smartmoving:
    block: false
```
then the server works aggain for your player.
Admins are not effected because they bypass this check, no matter if u set true or false.

Here the dev definatly needs to fix this problem with the option smartmoving. so we can set this option back to true (later in 4.2.3)
Why the config resets helps? the more easy answer.. if you look at a fresh config, you will notice all mod blockers are disabled by default...

**Comment by DoNotSpamPls** [comment]
Thanks for the report! The bug will be fixed ASAP, although next time please use the bug report template

**Comment by DoNotSpamPls** [comment]
Okay, so I've fixed this *temporarily* in c7326e0, but I won't be closing this issue yet. In the end I'd like to fix SmartMoving blocking as a whole, but for some reason it doesn't work at all. Even SBC (which is the plugin the author recommends for blocking) doesn't work 😦

**Comment by DoNotSpamPls** [comment]
I am removing SmartMoving semi-permanently from the code, since the mod hasn't been updated since 1.8.9 anyway, and I was unable to contact the developer. Even the plugin he recommends for blocking isn't able to block the mod in my testing.

**Comment by CloudeLecaw** [comment]
Well we long waiting for a working 1.13.1 version anyway :D
