### ISSUE TITLE
Block every tab command when writing /.

### ISSUE THREAD

**Issue by TheIntelloBox** [DoNotSpamPls/eZProtector#60]
Hello,

Currently my players just have to do / in the chat and they see every command by pressing TAB...

How to disable that ?

Best regards,
TheIntelloBox.

**Comment by DoNotSpamPls** [comment]
Use the new release of eZProtector and use the tab-complete module to remove commands that you don't want to be tab completable. If you want to remove all of them, set it to be in whitelist mode and add a non-existent command as the only entry in the list. However, that will break tab completion for commands like /tpa, which could be useful to players.

**Comment by TheIntelloBox** [comment]
Thanks for your answer.

If I set in whitelist mode and then in the whitelist I add tpa, tp, etc, will they be able to use TAB completion for these commands ?

**Comment by DoNotSpamPls** [comment]
Yes, that's the point of the whitelist mode :smiley:

**Comment by TheIntelloBox** [comment]
Hello, how to block AdvancedBans & Spigot commands in the TAB completion ? I've enabled the whitelist mods but they still appear.
