### ISSUE TITLE
whitelist players

### ISSUE THREAD

**Issue by MrMewlax** [DoNotSpamPls/eZProtector#62]
The ability to whitelist players that allows said players to join using any form of mod freely, this is necessary for players such as mods or chat mods that require to join with mods for their jobs but do not have /op

**Comment by DoNotSpamPls** [comment]
There is a permission for that - `ezprotector.bypass.mod.*`
All permissions for the plugin can be seen [here](https://github.com/DoNotSpamPls/eZProtector/blob/master/paper/src/main/resources/plugin.yml)
