### ISSUE TITLE
[Request] Add Badlion Support

### ISSUE THREAD

**Issue by mercurialmusic** [DoNotSpamPls/eZProtector#66]
**Describe the feature you'd like to have implemented**
Hey dude! Was wondering if it would be possible to block the Badlion client? I've noticed an uptick in usage and it allows things like minimaps etc. that we block in other mods, would make sense to be able to block this one too if possible.  Thanks for the consideration!

**Comment by DoNotSpamPls** [comment]
https://github.com/DoNotSpamPls/eZProtector/wiki/FAQ#will-you-implement-blocking-for-mod-name
