### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EvilSlime** [DoNotSpamPls/eZProtector#7]
https://hastebin.com/zuxanifoqi.vbs

**Comment by DoNotSpamPls** [comment]
Please use the report format - a log is insufficient. When does that error occur? On running a command, on joining? Be more elaborate.

**Comment by DoNotSpamPls** [comment]
@EvilSlime I am closing this issue, if there is still a problem, I'd like you to open a new issue and follow the bug report issue format
